---
- name: Get Uptime Information via SSH
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - juniper.device

  tasks:
    - name: Get uptime
      juniper.device.command:
        commands:
          - show system uptime
      register: response

    - name: Show-uptime
      debug:
        var: response.stdout_lines
