---
- name: Juniper Dynamic Command Playbook
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

  tasks:
    - name: Display command being executed
      debug:
        msg: "Executing command: {{ item }}"
      loop: "{{ survey_input }}"
      loop_control:
        label: "{{ item }}"  # Set the task label to the command for clarity

    - name: Execute commands chosen from the survey
      juniper_junos_command:
        commands: "{{ item }}"
      register: command_output
      loop: "{{ survey_input }}"
      loop_control:
        label: "{{ item }}"  # Set the task label to the command for clarity

    - name: Print the command output
      debug:
        var: command_output.results[item.index].stdout_lines
      loop: "{{ survey_input }}"
      loop_control:
        index_var: item_index
