---
- name: Juniper Image Upload
  hosts: all
  gather_facts: false
  roles:
    - juniper.junos
  collections:
    - juniper.device

  vars:
    pkg_dir: "/var/lib/awx/files"
    os_package: "{{ image }}"

  tasks:
    - name: Verify Current Version of OS_package
      juniper_junos_command:
        commands: "show version"
      register: version
      delegate_to: localhost  # Use localhost as the delegate

    - name: Display Current Version of OS_package
      debug:
        msg: "{{ version.stdout_lines }}"
      when: version.stdout_lines is defined

    - name: Show system storage space
      juniper_junos_command:
        commands: "show system storage"
      register: storage
      delegate_to: localhost  # Use localhost as the delegate

    - name: Display system storage space
      debug:
        msg: "{{ storage.stdout_lines }}"
      when: storage.stdout_lines is defined

    - name: Copy the OS package to the device
      junipernetworks.junos.junos_scp:
        src: "{{ pkg_dir }}/{{ os_package }}"
        dest: "/var/tmp/"
        host: "{{ inventory_hostname }}"  # Specify the target device
        user: "{{ ansible_user }}"  # Specify your username
        passwd: "{{ ansible_ssh_pass }}"  # Specify your password
        timeout: 600  # Specify a timeout if needed
      delegate_to: localhost  # Use localhost as the delegate

    - name: Verify the file was uploaded
      juniper_junos_command:
        commands: "file list detail /var/tmp/"
      register: storage
      delegate_to: localhost  # Use localhost as the delegate

    - name: Display the file list
      debug:
        msg: "{{ storage.stdout_lines }}"
      when: storage.stdout_lines is defined
