---
- name: Gathering System Information
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - juniper.device

  tasks:
    - name: Execute commands
      juniper.device.command:
        commands:
          - "show version"
      register: response

    - name: Print the command output
      debug:
        var: response.stdout_lines
