---
- name: Compare Juniper SRX Rollbacks
  hosts: all
  connection: ansible.netcommon.netconf
  gather_facts: no
  roles:
    - juniper.junos
  tasks:
    - name: Run show system rollback compare command
      juniper_junos_command:
        commands:
          - show system rollback compare {{ rollback_1 }} {{ rollback_2 }}
      register: result
