---
- name: Juniper Dynamic Command Playbook
  hosts: all
  #connection: ansible.netcommon.netconf
  connection: local
  gather_facts: no
  collections:
    - juniper.device

  tasks:
    - name: Execute commands chosen from the survey
      juniper.device.command:
        commands: "{{ item }}"
        timeout: "{{ timer }}"
      loop: "{{ survey_input }}"
