---
- name: Get Uptime Information via SSH
  hosts: all
  connection: ansible.netcommon.netconf
  gather_facts: false
  roles:
    - juniper.junos

  tasks:
    - name: Get uptime
      juniper_junos_command:
        commands:
          - show system uptime
      register: response

    - name: Show-uptime
      debug:
        var: response.stdout_lines
