---
- name: Reboot a Juniper Device
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - juniper.device

  tasks:
    - name: Performing a reboot in {{ survey_minutes }} minutes
      juniper.device.system:
        action: reboot
        in_min: "{{ survey_minutes }}"
      register: response
      notify: wait_reboot
      changed_when: response.changed

  handlers:
    - name: wait_reboot
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 830
        state: started
        timeout: 900
        delay: 1
