---
- name: Get Uptime Information via SSH
  hosts: all
  connection: juniper.device.pyez
  gather_facts: no
  roles:
    - juniper.junos

  tasks:
    - name: Get uptime
      juniper_junos_command:
        commands:
        - show system uptime
      register: response

    - name: Show uptime
      debug:
        var: response.stdout_lines