---
- name: Juniper Image Upload
  hosts: all
  connection: ansible.netcommon.netconf
  gather_facts: false
  roles:
    - juniper.junos
  collections:
    - juniper.device

  vars:
    pkg_dir: ""
    os_package: "{{ image }}"

  tasks:
    - name: Verify Current Version of OS_package
      juniper_junos_command:
        commands: "show version"
      register: version

    - name: Show system storage space
      juniper_junos_command:
        commands: "show system storage"
      register: storage

    - name: Copy the OS package to the device
      junipernetworks.junos.junos_scp:
        src: "{{ pkg_dir }}{{ os_package }}"
        dest: "/var/tmp/"
        provider:
          host: "{{ ansible_host }}"  # Specify the target device
          username: "{{ ansible_user }}"  # Specify your username
          password: "{{ ansible_ssh_pass }}"  # Specify your password
          timeout: 600  # Specify a timeout if needed

    - name: Verify the file was uploaded
      juniper_junos_command:
        commands: "file list detail /var/tmp/{{ image }}"
      register: storage
    
