---
- name: Juniper Cleanup and System Snapshot
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - juniper.device

  tasks:
  - name: Request System Storage Cleanup
    juniper.device.command:
      commands:
      - "request system storage cleanup"

  - name: Request System Rescuse
    juniper.device.command:
      commands:
      - "request system configuration rescue save"

  - name: Request System Snapshot
    juniper.device.command:
      commands:
      - "request system snapshot slice alternate"
      timeout: "300"
