---
- name: Perform a connectivity check
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

  vars:
    netconf_port: "22"

  tasks:
    - name: Checking NETCONF connectivity
      wait_for:
        timeout: 5
        host: "{{ ansible_host }}"
        port: "{{ netconf_port }}"