---
- name: Juniper Dynamic Command Playbook
  hosts: all
  connection: ansible.netcommon.netconf
  gather_facts: no
  roles:
    - juniper.junos

  tasks:
    - name: Execute commands chosen from the survey
      juniper_junos_command:
        commands: "{{ item }}"
        provider:
          timeout: "{{ timer }}"
      loop: "{{ survey_input }}"
