---
- name: Juniper Dynamic Command Playbook
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

  tasks:
    - name: Execute commands chosen from the survey
      juniper_junos_command:
        commands: "{{ item }}"
#      register: response
      loop: "{{ survey_input }}"

 #   - name: Print the command output
 #     debug:
 #       var: response.results | map(attribute='stdout_lines') | list
