#region Copywrite
        #######################################################################
        #                                                                     #
        #               Written by Brian Giuffre                              #
        #                CIO-Radio - 12/16/2020                               #
        #                                                                     #
        #                                                                     #
        #                            \                                        #
        #                             \                                       #
        #                              \\                                     #
        #                               \\                                    #
        #                                >\/7                                 #
        #                            _.-(6'  \                                #
        #                           (=___._/` \                               #
        #                                )  \ |                               #
        #                               /   / |                               #
        #                              /    > /                               #
        #                             j    < _\                               #
        #                         _.-' :      ``.                             #
        #                         \ r=._\        `.                           #
        #                        <`\\_  \         .`-.                        #
        #                         \ r-7  `-. ._  ' .  `\                      #
        #                          \`,      `-.`7  7)   )                     #
        #                           \/         \|  \'  / `-._                 #
        #                                      ||    .'                       #
        #                                       \\  (                         #
        #                                        >\  >                        #
        #                                    ,.-' >.'                         #
        #                                   <.'_.''                           #
        #                                     <'                              #
        #                                                                     #
        #######################################################################
#endregion Copywrite

---
- name: Restore to Factory Defaults
  hosts: localhost
  roles:
    - juniper.junos
  connection: local
  gather_facts: no

  vars_prompt:
    - name: host_ip
      prompt: Please enter the target host IP
      private: no

  tasks:
    - name: Reboot all REs and restore to Factory Default appliance "{{ host_ip }}"
      juniper_junos_system:
        action: "zeroize"
        provider:
          host: "{{ host_ip }}"
          port: "22"