---
- name: Juniper Cleanup and System Snapshot
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

  tasks:
  - name: Request System Storage Cleanup
    juniper_junos_command:
      commands:
      - "request system storage cleanup"
    register: response
    async: 300 # Maximum runtime in seconds (5 minutes)
    poll: 15   # Check every 15 seconds if the task is completed

  - name: Display Storage Cleanup Results
    debug:
      var: response.stdout_lines

  - name: Request System Rescuse
    juniper_junos_command:
      commands:
      - "request system configuration rescue save"
    async: 300 # Maximum runtime in seconds (5 minutes)
    poll: 15   # Check every 15 seconds if the task is completed

  - name: Request System Snapshot
    juniper_junos_command:
      commands:
      - "request system snapshot slice alternate"
    async: 300 # Maximum runtime in seconds (5 minutes)
    poll: 15   # Check every 15 seconds if the task is completed
