---
- name: Compare Juniper SRX Rollbacks
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - juniper.device
  tasks:
    - name: Running show system rollback compare {{ rollback_1 }} {{ rollback_2 }} command
      juniper.device.command:
        commands:
          - show system rollback compare {{ rollback_1 }} {{ rollback_2 }}
      register: result
