---
- name: Juniper Configuration Backup Playbook
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - juniper.device

  tasks:
    - name: Execute show configuration command
      juniper.device.command:
        commands: "show configuration"

    - name: Execute show configuration command with format set
      juniper.device.command:
        commands: "show configuration | display set"
