---
- name: Gather all Juniper SRX Commits
  hosts: all
  connection: ansible.netcommon.netconf
  gather_facts: no
#  roles:
#    - juniper.junos
  collections:
 #   - junipernetworks.junos
    - juniper.device
  tasks:
    - name: Running show system commit command
 #     juniper_junos_command:
 #       commands:
 #         - show system commit
 #     junipernetworks.junos.junos_command:
 #       commands:
 #         - show system commit
      juniper.device.command:
        commands:
          - show system commit
      register: results
