---
- name: Juniper Dynamic Command Playbook
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

  tasks:

    - name: Execute command chosen from the survey
      juniper_junos_command:
        commands: "{{ survey_input }}"
      register: response

    - name: Print the command output
      debug:
        var: response.stdout_lines
