---
- name: Gather all Juniper SRX Commits
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - juniper.device
  tasks:
    - name: Running show system commit command
      juniper.device.command:
        commands:
          - show system commit
      register: results
