---
- name: Get Device Facts
  hosts: all
  roles:
    - juniper.junos
  gather_facts: no

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: host={{ inventory_hostname }} port=830 timeout=5