---
- name: Perform a connectivity check
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

  tasks:
    - name: Checking NETCONF connectivity
      wait_for: host={{ inventory_hostname }} port=830 timeout=5