---
- name: Gathering System Information
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

  tasks:

    - name: Execute commands
      juniper.junos.command:
        commands:
          - "show version"
      register: response

    - name: Print the command output
      debug:
        var: response.stdout_lines