---
- name: Gathering System Information
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Execute three commands
      junos_command:
        commands:
          - "show version"
          - "show system uptime"
          - "show interface terse"
      register: response