---
- name: Gathering System Information
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - juniper.device

  tasks:

    - name: check connectivity
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 830
        timeout: 300

    - name: Execute commands
      juniper.device.command:
        commands:
          - "show version"
      register: response

    - name: Print the command output
      debug:
        var: response.stdout_lines